modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL=""

[[mods]]
modId="arcadiaadminpanel"
version="1.2.0"
displayName="Arcadia Admin Panel"
authors="vyrriox"
description='''
Arcadia Admin Panel - Lightweight & Optimized Server Management
Steampunk-themed admin interface powered by Arcadia Lib
Developed by vyrriox
'''

[[dependencies.arcadiaadminpanel]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcadiaadminpanel]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.arcadiaadminpanel]]
modId="arcadia_lib"
type="required"
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"
