modLoader="neoforge"
loaderVersion="[21,)"
license="All rights reserved"
issueTrackerURL=""

[[mods]]
modId="arcadiaadminpannel"
version="1.0.0"
displayName="Arcadia Admin Panel"
authors="vyrriox"
description='''
Arcadia Admin Panel - Advanced & Optimized Server Management.
Developed by vyrriox.
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.arcadiaadminpannel]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcadiaadminpannel]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
