package com.arcadia.adminpanel.util;

import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;

import java.util.HashMap;
import java.util.Map;

/**
 * Localization helper for Admin Panel — EN and FR.
 *
 * @author vyrriox
 */
public final class LanguageHelper {

    private static final Map<String, Map<String, String>> translations = new HashMap<>();

    static {
        Map<String, String> en = new HashMap<>();
        en.put("menu.title", "Admin Panel");
        en.put("menu.filter.all", "Filter: ALL");
        en.put("menu.filter.online", "Filter: ONLINE");
        en.put("player.online", "Online");
        en.put("player.offline", "Offline");
        en.put("detail.title", "Player: %s");
        en.put("detail.homes", "Homes");
        en.put("detail.tp_history", "Teleport History");
        en.put("homes.none", "No Homes");
        en.put("action.tp", "Teleport to Player");
        en.put("action.tp_here", "Teleport Player Here");
        en.put("action.tp_last", "TP Last Known Location");
        en.put("action.kick", "Kick Player");
        en.put("action.ban", "Ban Player");
        en.put("action.unban", "Unban Player");
        en.put("action.back", "Back to List");
        en.put("action.warn", "Warn Player");
        en.put("action.warn_list", "View Warns");
        en.put("action.search", "Search Players");
        en.put("action.search.hint", "Click to search by name");
        en.put("action.search.prompt", "Type a player name to search (or 'cancel'):");
        en.put("action.search.clear", "Clear Search");
        en.put("action.search.current", "Current filter:");
        en.put("action.cancelled", "Action cancelled.");
        en.put("info.full", "Full Information");
        en.put("info.banned", "Banned");
        en.put("info.whitelisted", "Whitelisted");
        en.put("info.last_seen", "Last Seen");
        en.put("misc.yes", "YES");
        en.put("misc.no", "NO");
        en.put("misc.click_tp", "Click to Teleport");
        en.put("misc.confirm", "Click again to confirm!");
        en.put("action.invsee", "View Inventory");
        en.put("action.resetprog", "Reset Progress");
        en.put("action.clearinv", "Clear Inventory");
        en.put("msg.inv_cleared", "Inventory cleared for %s");
        en.put("warn.prompt", "Type the warn reason in chat (or 'cancel'):");
        en.put("warn.prompt.cancel", "Type 'cancel' to abort.");
        en.put("warn.success", "Player warned successfully.");
        en.put("warn.list.title", "Warns: %s");
        en.put("warn.list.empty", "No warnings found.");
        en.put("warn.item.title", "Warn #%d");
        en.put("warn.item.by", "By: %s");
        en.put("warn.item.reason", "Reason: %s");
        en.put("warn.item.date", "Date: %s");
        en.put("warn.title", "WARNING");
        en.put("warn.subtitle", "You have been warned!");
        en.put("warn.notification", "You have been warned by %s");
        en.put("warn.deleted", "Warning #%d deleted for player %s.");
        en.put("warn.click_delete", "Click to delete");
        en.put("warn.cleared", "All warnings cleared for %s (%d removed).");
        en.put("error.invalid_index", "Invalid warning index.");
        en.put("error.no_warns", "This player has no warnings.");
        en.put("error.invalid_target", "Invalid target.");
        en.put("error.player_only", "This command can only be used by players.");
        en.put("action.mute", "Mute Player");
        en.put("action.unmute", "Unmute Player");
        en.put("mute.hint", "Click to mute for 10 minutes");
        en.put("mute.remaining", "Time remaining:");
        en.put("mute.reason", "Reason:");
        en.put("mute.feedback", "You are muted. Remaining: %time% — Reason: %reason%");
        en.put("staff.chat.enabled", "Staff chat enabled. All messages go to staff channel.");
        en.put("staff.chat.disabled", "Staff chat disabled. Messages go to public chat.");
        en.put("staff.online", "Staff online (%d):");
        en.put("staff.none_online", "No staff members online.");
        en.put("action.jail", "Jail Player");
        en.put("action.unjail", "Unjail Player");
        en.put("jail.hint", "Click to jail for 30 minutes");
        en.put("jail.remaining", "Time remaining:");
        en.put("jail.reason.label", "Reason:");
        en.put("jail.permanent", "Permanent");
        en.put("jail.location.set", "Jail location set at your current position!");
        en.put("jail.no_location", "No jail location set! Use /arcadia_adminpanel setjail first.");
        en.put("jail.success", "Jailed %player% for %time%.");
        en.put("jail.unjail.success", "Unjailed %player%.");
        en.put("jail.not_jailed", "%player% is not jailed.");
        en.put("jail.notify", "You have been jailed! Duration: %time% — Reason: %reason%");
        en.put("jail.notify.permanent", "You have been permanently jailed! Reason: %reason%");
        en.put("jail.released", "You have been released from jail!");
        en.put("jail.login.reminder", "You are still jailed. Remaining: %time% — Reason: %reason%");
        en.put("jail.blocked.command", "You cannot use commands while jailed.");
        en.put("jail.list.empty", "No players currently jailed.");
        en.put("jail.list.header", "Jailed players (%count%):");
        en.put("nav.previous", "Previous");
        en.put("nav.next", "Next");
        en.put("reload.start", "Reloading admin panel data...");
        en.put("reload.done", "Reload complete!");
        en.put("error.open_panel", "Failed to open admin panel: %s");
        en.put("warn.reason_prefix", "Reason:");
        en.put("warn.list_console", "Warnings for %s: %d");
        en.put("misc.admin_action", "Admin Action");
        en.put("misc.unknown", "Unknown");
        en.put("misc.dim", "Dim:");
        en.put("misc.pos", "Pos:");
        en.put("misc.server", "Server:");
        en.put("misc.warns_label", "Warns:");
        en.put("misc.warn_count", "%d warn(s)");
        en.put("tp.success", "Teleported to %.0f, %.0f, %.0f");
        en.put("search.placeholder", "Search...");
        en.put("info.last_login", "Last login:");
        en.put("info.last_logout", "Last logout:");
        en.put("info.first_seen", "First seen:");
        en.put("team.browse", "Browse Teams");
        en.put("team.browse.hint", "View all FTB Teams (parties + server teams)");
        en.put("team.list.title", "FTB Teams");
        en.put("team.list.empty", "No teams found.");
        en.put("team.detail.title", "Team Details");
        en.put("team.not_found", "Team not found (data may be stale, reload).");
        en.put("team.unavailable", "FTB Teams not detected");
        en.put("team.unavailable.hint", "The ftbteams data dir was not found on this server.");
        en.put("team.view", "View Team");
        en.put("team.name", "Name:");
        en.put("team.type", "Type:");
        en.put("team.members", "Members:");
        en.put("team.rank", "Rank:");
        en.put("team.click.view", "Click to view members");
        en.put("team.click.tp", "Right-click: TP to last-seen position");
        en.put("team.claims", "Claims:");
        en.put("team.force_loaded", "Force-loaded:");
        en.put("warn.join.header", "You have %count% active warning(s):");
        en.put("warn.join.expires", "expires in");
        en.put("warn.join.more", "more — use /arcadia_adminpanel checkwarn to view all.");
        en.put("warn.join.cmd_hint", "To view your warnings, run:");
        en.put("jail.blocked.teleport", "You cannot use teleport items or blocks while jailed.");
        en.put("warn.join.cmd_hover", "Click to run the command.");
        en.put("baton.tooltip.line1", "Right-click a player to jail them for 30 minutes.");
        en.put("baton.tooltip.line2", "Staff only — requires arcadia.adminpanel.jail.");
        en.put("baton.reason", "Whacked with a Jail Baton");
        en.put("baton.no_perm", "You do not have permission to use the Jail Baton.");
        en.put("baton.no_self", "You cannot baton yourself.");
        en.put("baton.no_staff", "You cannot baton other staff members.");
        en.put("baton.given", "Jail Baton added to your inventory.");
        en.put("announce.empty", "Announcement title cannot be empty.");
        en.put("announce.success", "Announcement sent to %count% player(s).");
        // ── 1.2.5 ──────────────────────────────────────────────────────────
        en.put("action.nextspawn", "Next-Login Spawn");
        en.put("nextspawn.hint", "Left-click: spawn this player at your position on their next login.");
        en.put("nextspawn.set_to", "Set to:");
        en.put("nextspawn.left_update", "Left-click: update to your position");
        en.put("nextspawn.right_clear", "Right-click: clear");
        en.put("nextspawn.set", "Next-login spawn set for %player%.");
        en.put("nextspawn.cleared", "Cleared next-login spawn for %player%.");
        en.put("nextspawn.none", "No next-login spawn was set for %player%.");
        en.put("nextspawn.applied", "An admin moved your next-login spawn point.");
        en.put("nextspawn.list.empty", "No pending next-login spawns.");
        en.put("nextspawn.list.header", "Pending next-login spawns (%count%):");
        en.put("action.gamemode", "Game Mode");
        en.put("gamemode.current", "Current:");
        en.put("gamemode.cycle", "Click to cycle game mode");
        en.put("action.heal", "Heal / Feed");
        en.put("heal.hint", "Left-click: heal · Right-click: feed");
        en.put("heal.done", "Healed %player%.");
        en.put("feed.done", "Fed %player%.");
        en.put("team.filter.show_players", "Show player teams");
        en.put("team.filter.hide_players", "Hide player teams");
        en.put("team.filter.players_hint", "Toggle per-player (personal) teams in the list");
        en.put("team.member.actions", "Left-click: manage / moderate · Right-click: TP to last-seen");
        en.put("team.gather", "Gather online members");
        en.put("team.gather.hint", "Teleport every online member of this team to you.");
        en.put("team.gather.notify", "You were summoned by %admin%.");
        en.put("team.gather.done", "Gathered %count% online member(s) of %team%.");
        en.put("team.message", "Message the team");
        en.put("team.message.hint", "Type a line that's sent to every online member.");
        en.put("team.message.prompt", "Type the message to send to %team% (or 'cancel'):");
        en.put("team.message.prefix", "Staff:");
        en.put("team.message.sent", "Message delivered to %count% online member(s) of %team%.");
        en.put("jail.radius.current", "Jail zone radius: %radius% blocks (anti-escape: %state%)");
        en.put("jail.radius.set", "Jail zone radius set to %radius% blocks (anti-escape enabled).");
        en.put("loginqueue.state", "Login queue is currently %state%.");
        en.put("loginqueue.set", "Login queue turned %state%.");
        en.put("loginqueue.invalid", "Invalid state — use 'on' or 'off'.");
        // ── Name tags ───────────────────────────────────────────────────────
        en.put("nametag.set.color", "Set %player%'s name colour to %value%.");
        en.put("nametag.set.rgb", "Set %player%'s name to RGB %value%.");
        en.put("nametag.set.gradient", "Set %player%'s name to a %value%-stop gradient.");
        en.put("nametag.set.effect", "Set %player%'s name effect to %value%.");
        en.put("nametag.set.style_on", "Enabled %value% on %player%'s name.");
        en.put("nametag.set.style_off", "Disabled %value% on %player%'s name.");
        en.put("nametag.set.speed", "Set %player%'s name animation speed to %value%.");
        en.put("nametag.name.set", "Set %player%'s display name to '%value%'.");
        en.put("nametag.name.cleared", "Cleared %player%'s custom display name (back to their real name).");
        en.put("nametag.name.too_long", "That pseudo is too long (max 32 characters).");
        en.put("nametag.grade.on", "%player%'s grade is now shown next to their name.");
        en.put("nametag.grade.off", "%player%'s grade is now hidden next to their name.");
        en.put("nametag.reset", "Cleared %player%'s name styling.");
        en.put("nametag.reset_none", "%player% had no name styling.");
        en.put("nametag.show", "%player%: name=%name% grade=%grade% effect=%effect% colours=[%colors%] speed=%speed% styles=%flags%");
        en.put("nametag.show_none", "%player% uses the default name (no styling).");
        en.put("nametag.exempt_on", "%player% is now exempt — their name is always visible.");
        en.put("nametag.exempt_off", "%player% is no longer exempt from name hiding.");
        en.put("nametag.hide.state", "Hide names behind walls is currently %state%.");
        en.put("nametag.hide.set", "Hide names behind walls turned %state%.");
        en.put("nametag.hideall.state", "Event name blackout is currently %state%.");
        en.put("nametag.hideall.set", "Event name blackout turned %state% — every player's name is now affected.");
        en.put("nametag.forcehide_on", "%player%'s name is now permanently hidden for everyone.");
        en.put("nametag.forcehide_off", "%player%'s name is no longer permanently hidden.");
        en.put("nametag.invalid_color", "Invalid colour name. Use a vanilla colour like red, gold, aqua…");
        en.put("nametag.invalid_hex", "Invalid hex colour. Use #RRGGBB (e.g. #FF8800).");
        en.put("nametag.invalid_effect", "Unknown effect. Try: solid, gradient, rainbow, breathing, chase, wave, blink, fade, typewriter, random.");
        en.put("nametag.invalid_flag", "Unknown style flag. Use: bold, italic, underline, strikethrough, obfuscated.");
        en.put("disguise.set", "Disguised %player% as %value%.");
        en.put("disguise.cleared", "Removed %player%'s disguise.");
        en.put("disguise.none", "%player% was not disguised.");
        en.put("disguise.invalid_entity", "Unknown entity type '%value%'. Use an id like minecraft:pig.");
        en.put("disguise.not_living", "'%value%' is not a living mob and can't be used as a disguise.");
        // ── 1.3.0 ───────────────────────────────────────────────────────────
        en.put("action.close", "Close");
        en.put("list.empty", "Nothing to show");
        en.put("misc.on", "ON");
        en.put("misc.off", "OFF");
        en.put("error.player_offline", "That player is not connected.");

        en.put("tools.title", "Staff Tools");
        en.put("tools.hint", "Server-wide tools and your own toggles");
        en.put("tools.status", "Server Status");
        en.put("tools.status.tps", "TPS");
        en.put("tools.status.mspt", "MSPT");
        en.put("tools.status.players", "Players");
        en.put("tools.status.memory", "Memory");
        en.put("tools.status.entities", "Entities");
        en.put("tools.players", "Player List");
        en.put("tools.players.hint", "Back to the player grid");
        en.put("tools.audit", "Audit Log");
        en.put("tools.audit.entries", "entries");
        en.put("tools.bans", "Ban List");
        en.put("tools.bans.count", "bans");
        en.put("tools.watchlist", "Watchlist");
        en.put("tools.watchlist.count", "flagged");
        en.put("tools.sessions", "Playtime");
        en.put("tools.sessions.hint", "Sessions and playtime ranking");
        en.put("tools.afk", "AFK Players");
        en.put("tools.afk.count", "idle");
        en.put("tools.alts", "Shared Connections");
        en.put("tools.alts.count", "groups");
        en.put("tools.alts.shared", "matching accounts");
        en.put("tools.alts.privacy", "No address is ever stored or shown");
        en.put("tools.clientmods", "Client Mods");
        en.put("tools.clientmods.count", "reports");
        en.put("tools.performance", "Performance");
        en.put("tools.performance.hint", "TPS, hot chunks, heavy players");
        en.put("tools.chunks", "Chunk Browser");
        en.put("tools.chunks.hint", "Claims and force-loaded chunks");
        en.put("tools.world", "World Control");
        en.put("tools.world.hint", "Time, weather, difficulty, game rules");
        en.put("tools.chat.lock", "Lock Chat");
        en.put("tools.chat.unlock", "Unlock Chat");
        en.put("tools.chat.lock.hint", "Freeze public chat");
        en.put("tools.chat.locked_by", "Locked by");
        en.put("tools.chat.clear", "Clear Chat");
        en.put("tools.chat.clear.hint", "Scroll everyone's chat away");
        en.put("tools.restart", "Scheduled Restart");
        en.put("tools.restart.hint", "Left: in 15 min, right: in 5 min");
        en.put("tools.restart.pending", "Restarting in");
        en.put("tools.restart.click", "Click again to cancel");
        en.put("tools.broadcast", "Auto Broadcast");
        en.put("tools.broadcast.count", "messages");
        en.put("tools.vanish", "Vanish");
        en.put("tools.silent", "Silent Mode");
        en.put("tools.silent.hint", "No public announcement, still audited");
        en.put("tools.cmdspy", "Command Spy");
        en.put("tools.socialspy", "Social Spy");
        en.put("tools.loginqueue", "Login Queue");
        en.put("tools.loginqueue.hint", "Post-reboot connection throttle");
        en.put("tools.loginqueue.auto", "Automatic window:");
        en.put("tools.selection", "Selection");
        en.put("tools.selection.count", "selected");
        en.put("tools.selection.hint", "Shift-click heads to select");
        en.put("tools.back", "Return");
        en.put("tools.back.count", "positions saved");
        en.put("tools.radar", "Proximity Radar");
        en.put("tools.radar.hint", "Who is nearby");

        en.put("tools.player", "Player Tools");
        en.put("tools.player.hint", "History, notes, freeze, inventory and more");
        en.put("tools.player.open", "Click to open");
        en.put("tools.player.rows", "Investigate / Intervene / Assist, one row each");
        en.put("tools.group.investigate", "Investigate");
        en.put("tools.group.investigate.hint", "Find out what happened");
        en.put("tools.group.intervene", "Intervene");
        en.put("tools.group.intervene.hint", "Act on this player now");
        en.put("tools.group.assist", "Assist");
        en.put("tools.group.assist.hint", "Give something back or reach them");
        en.put("tools.group.server", "Server");
        en.put("tools.group.server.hint", "Performance, world, chat and scheduling");
        en.put("tools.group.self", "Your Toggles");
        en.put("tools.group.self.hint", "Switches that apply to you alone");
        en.put("tools.requires_online", "Needs the player connected");
        en.put("tools.offline_release", "They are offline: releasing lifts it for their next login");
        en.put("tools.deaths.hint", "Their last deaths and what they carried");
        en.put("tools.back.sheet", "Back to the player sheet");
        en.put("tools.history", "Sanction History");
        en.put("tools.history.count", "sanctions");
        en.put("tools.notes", "Staff Notes");
        en.put("tools.watch.add", "Add to Watchlist");
        en.put("tools.watch.remove", "Remove from Watchlist");
        en.put("tools.freeze", "Freeze");
        en.put("tools.freeze.hint", "Hold the player for a screenshare");
        en.put("tools.unfreeze", "Release");
        en.put("tools.unfreeze.hint", "End the screenshare");
        en.put("tools.spectate", "Spectate");
        en.put("tools.spectate.stop", "Stop Spectating");
        en.put("tools.spectate.hint", "Returns you where you were");
        en.put("tools.tempban", "Temporary Ban");
        en.put("tools.tempban.hint", "Right-click for a permanent ban");
        en.put("tools.templates", "Sanction Templates");
        en.put("tools.templates.hint", "Pre-written reasons with escalation");
        en.put("tools.select.add", "Add to Selection");
        en.put("tools.select.remove", "Remove from Selection");
        en.put("tools.invedit", "Inventory Editor");
        en.put("tools.invedit.hint", "View and modify, then save");
        en.put("tools.deaths", "Death Snapshots");
        en.put("tools.give", "Give Item");
        en.put("tools.give.hint", "Left: held item, right: by id");
        en.put("tools.mail", "Offline Mail");

        en.put("menu.filter", "Filter:");
        en.put("menu.legend", "How this screen works");
        en.put("menu.legend.open", "Left-click a head: open their sheet");
        en.put("menu.legend.select", "Right-click or shift-click a head: add to the selection");
        en.put("menu.legend.cycle", "Filter and sort: left-click steps forward, right-click back");
        en.put("menu.legend.colours", "Name colour:");
        en.put("menu.legend.online", "online");
        en.put("menu.legend.afk", "AFK");
        en.put("menu.legend.offline", "offline");
        en.put("menu.legend.selected", "selected");
        en.put("menu.filter.results", "results");
        en.put("menu.filter.cycle", "Right-click to go back");
        en.put("menu.filter.all", "All");
        en.put("menu.filter.online", "Online");
        en.put("menu.filter.offline", "Offline");
        en.put("menu.filter.jailed", "Jailed");
        en.put("menu.filter.muted", "Muted");
        en.put("menu.filter.banned", "Banned");
        en.put("menu.filter.warned", "Warned");
        en.put("menu.filter.watched", "Watched");
        en.put("menu.filter.frozen", "Frozen");
        en.put("menu.filter.vanished", "Vanished");
        en.put("menu.filter.afk", "AFK");
        en.put("menu.filter.selected", "Selected");
        en.put("menu.sort", "Sort:");
        en.put("menu.sort.cycle", "Right-click to go back");
        en.put("menu.sort.name", "Name");
        en.put("menu.sort.last_seen", "Last seen");
        en.put("menu.sort.playtime", "Playtime");
        en.put("menu.sort.warns", "Warns");
        en.put("menu.select.hint", "Shift-click or right-click to select");
        en.put("menu.mark.jailed", "Jailed");
        en.put("menu.mark.muted", "Muted");
        en.put("menu.mark.frozen", "Frozen");
        en.put("menu.mark.vanished", "Vanished");
        en.put("menu.mark.watched", "Watched");
        en.put("menu.mark.warns", "warns");

        en.put("audit.title", "Audit Log");
        en.put("audit.empty", "No action recorded yet.");
        en.put("audit.by", "By");
        en.put("audit.duration", "Duration:");
        en.put("audit.detail", "Detail:");
        en.put("audit.silent", "silent");
        en.put("audit.click_actor", "Right-click: this staff member's actions");
        en.put("audit.filter", "Filter");
        en.put("audit.filter.clear", "Click to see everything");
        en.put("audit.scope.all", "All actions");
        en.put("audit.scope.target", "One player");
        en.put("audit.scope.actor", "One staff member");
        en.put("audit.action.warn", "warned");
        en.put("audit.action.warn_delete", "deleted a warn from");
        en.put("audit.action.warn_clear", "cleared the warns of");
        en.put("audit.action.mute", "muted");
        en.put("audit.action.unmute", "unmuted");
        en.put("audit.action.kick", "kicked");
        en.put("audit.action.ban", "banned");
        en.put("audit.action.tempban", "temp-banned");
        en.put("audit.action.unban", "unbanned");
        en.put("audit.action.jail", "jailed");
        en.put("audit.action.unjail", "released");
        en.put("audit.action.freeze", "froze");
        en.put("audit.action.unfreeze", "unfroze");
        en.put("audit.action.vanish", "toggled vanish on");
        en.put("audit.action.spectate", "spectated");
        en.put("audit.action.spy", "used a spy feed on");
        en.put("audit.action.invsee", "viewed the inventory of");
        en.put("audit.action.clear_inv", "cleared the inventory of");
        en.put("audit.action.inv_edit", "edited the inventory of");
        en.put("audit.action.restore_death", "restored a death of");
        en.put("audit.action.give_item", "gave an item to");
        en.put("audit.action.reset_progress", "reset the progress of");
        en.put("audit.action.gamemode", "changed the game mode of");
        en.put("audit.action.heal", "healed");
        en.put("audit.action.teleport", "teleported");
        en.put("audit.action.next_spawn", "set a next-login spawn for");
        en.put("audit.action.note_add", "added a note on");
        en.put("audit.action.note_delete", "deleted a note on");
        en.put("audit.action.watch_add", "flagged");
        en.put("audit.action.watch_remove", "unflagged");
        en.put("audit.action.mail_send", "sent mail to");
        en.put("audit.action.announce", "announced");
        en.put("audit.action.chat_lock", "changed the chat lock");
        en.put("audit.action.chat_clear", "cleared the chat");
        en.put("audit.action.world_edit", "changed a world setting");
        en.put("audit.action.restart", "changed the restart schedule");
        en.put("audit.action.bulk", "ran a bulk action");
        en.put("audit.action.nametag", "changed the name tag of");
        en.put("audit.action.disguise", "disguised");
        en.put("audit.action.login_queue", "changed the login queue");
        en.put("audit.action.setjail", "moved the jail");
        en.put("audit.action.reload", "reloaded the panel");

        en.put("history.title", "History");
        en.put("history.empty", "No sanction on record.");
        en.put("history.active", "Currently active");
        en.put("history.warns", "Warns:");
        en.put("history.sanctions", "Other sanctions:");
        en.put("history.total", "Total:");
        en.put("history.audit", "Full audit trail");
        en.put("history.audit.hint", "Every action, not just sanctions");

        en.put("notes.title", "Notes");
        en.put("notes.empty", "No note yet.");
        en.put("notes.count", "notes");
        en.put("notes.add", "Add a note");
        en.put("notes.add.hint", "Type it in chat");
        en.put("notes.pin.hint", "Start with ! to pin it");
        en.put("notes.pinned", "Pinned");
        en.put("notes.click_delete", "Right-click to delete");
        en.put("note.added", "Note added on %player%.");

        en.put("watchlist.title", "Watchlist");
        en.put("watchlist.empty", "Nobody is flagged.");
        en.put("watchlist.click", "Left: sheet, right: unflag");
        en.put("watchlist.added", "%player% is now on the watchlist.");
        en.put("watchlist.removed", "%player% is off the watchlist.");
        en.put("watchlist.not_watched", "%player% was not flagged.");
        en.put("watchlist.join", "Watched player %player% just connected (flagged by %by%)");
        en.put("watchlist.flagged", "On the watchlist");

        en.put("banlist.title", "Bans");
        en.put("banlist.empty", "Nobody is banned.");
        en.put("banlist.permanent", "Permanent");
        en.put("banlist.expires", "Expires in");
        en.put("banlist.click_unban", "Click to unban");
        en.put("banlist.unbanned", "%player% has been unbanned.");
        en.put("ban.applied", "%player% has been banned.");

        en.put("sessions.title", "Playtime");
        en.put("sessions.empty", "No session recorded.");
        en.put("sessions.playtime", "Playtime:");
        en.put("sessions.count", "sessions");
        en.put("sessions.average", "Average:");
        en.put("sessions.last", "Last login:");
        en.put("sessions.sort", "Sort");
        en.put("sessions.sort.playtime", "By playtime");
        en.put("sessions.sort.recent", "By last login");

        en.put("afk.title", "AFK Players");
        en.put("afk.empty", "Nobody is idle.");
        en.put("afk.duration", "Idle for");
        en.put("afk.click", "Left: sheet, right: teleport");
        en.put("afk.threshold", "Threshold");

        en.put("alts.title", "Shared Connections");
        en.put("alts.empty", "No shared connection found.");
        en.put("alts.group", "Group");
        en.put("alts.accounts", "accounts");
        en.put("alts.has_banned", "Includes a banned account");
        en.put("alts.click", "Click to see the accounts");
        en.put("alts.privacy.title", "About this data");
        en.put("alts.privacy.line1", "Accounts are grouped by a salted hash.");
        en.put("alts.privacy.line2", "No address is stored or displayed.");
        en.put("alt.ban_evasion", "%player% shares a connection with banned account(s): %accounts%");

        en.put("clientmods.title", "Client Mods");
        en.put("clientmods.empty", "No client has reported.");
        en.put("clientmods.none", "This client reported nothing.");
        en.put("clientmods.no_report", "No report (mod not installed)");
        en.put("clientmods.mods", "mods");
        en.put("clientmods.click", "Click to see the list");
        en.put("clientmods.declared", "Declared by the client");
        en.put("clientmods.blacklisted", "On the blacklist");
        en.put("clientmods.flagged_short", "Blacklisted mod detected");
        en.put("clientmods.flagged", "%player% is running a blacklisted mod: %mods%");
        en.put("clientmods.disclaimer.title", "About this data");
        en.put("clientmods.disclaimer.line1", "Self-declared by the client.");
        en.put("clientmods.disclaimer.line2", "A modified client can lie.");

        en.put("perf.title", "Performance");
        en.put("perf.summary", "Summary");
        en.put("perf.mspt_mean", "Average MSPT:");
        en.put("perf.mspt_peak", "Peak MSPT:");
        en.put("perf.entities_total", "Total entities:");
        en.put("perf.chunks_total", "Loaded chunks:");
        en.put("perf.sampled", "Sampled");
        en.put("perf.entities", "entities");
        en.put("perf.chunks", "chunks");
        en.put("perf.forced", "forced");
        en.put("perf.hot_chunks", "Hot Chunks");
        en.put("perf.hot_chunks.hint", "Highest entity concentration");
        en.put("perf.chunk", "Chunk");
        en.put("perf.nearest", "Nearest:");
        en.put("perf.nearby", "Nearby entities:");
        en.put("perf.afk", "AFK");
        en.put("perf.refresh", "Recompute");

        en.put("chunks.title", "Chunks");
        en.put("chunks.no_teams", "No FTB Chunks data.");
        en.put("chunks.no_forced", "No forced chunk.");
        en.put("chunks.claims", "Claims:");
        en.put("chunks.forced", "Force-loaded:");
        en.put("chunks.members", "Members:");
        en.put("chunks.block_pos", "Block");
        en.put("chunks.view", "View");
        en.put("chunks.view.teams", "By team");
        en.put("chunks.view.forced", "Vanilla forced chunks");
        en.put("chunks.summary", "Totals");
        en.put("chunks.vanilla_forced", "Vanilla forced:");

        en.put("world.title", "World Control");
        en.put("world.current_time", "Time:");
        en.put("world.current_weather", "Weather:");
        en.put("world.scope_dimension", "Applies to this dimension");
        en.put("world.scope_server", "Applies server-wide");
        en.put("world.time.dawn", "Dawn");
        en.put("world.time.day", "Day");
        en.put("world.time.noon", "Noon");
        en.put("world.time.dusk", "Dusk");
        en.put("world.time.night", "Night");
        en.put("world.time.midnight", "Midnight");
        en.put("world.weather.clear", "Clear");
        en.put("world.weather.rain", "Rain");
        en.put("world.weather.thunder", "Thunder");
        en.put("world.difficulty", "Difficulty:");
        en.put("world.difficulty.hint", "Click to cycle");
        en.put("world.difficulty.peaceful", "Peaceful");
        en.put("world.difficulty.easy", "Easy");
        en.put("world.difficulty.normal", "Normal");
        en.put("world.difficulty.hard", "Hard");

        en.put("radar.title", "Radar");
        en.put("radar.empty", "Nobody within range.");
        en.put("radar.blocks", "blocks");
        en.put("radar.range", "Range");
        en.put("radar.vanished", "Vanished");
        en.put("radar.click_detail", "Right-click: player sheet");

        en.put("bulk.title", "Bulk Actions");
        en.put("bulk.empty", "Nothing selected. Shift-click heads in the grid.");
        en.put("bulk.targets", "targets");
        en.put("bulk.click_remove", "Click to remove");
        en.put("bulk.message", "Message everyone");
        en.put("bulk.gather", "Gather here");
        en.put("bulk.heal", "Heal everyone");
        en.put("bulk.warn", "Warn everyone");
        en.put("bulk.kick", "Kick everyone");
        en.put("bulk.kick.hint", "Click twice to confirm");
        en.put("bulk.clear", "Clear selection");
        en.put("bulk.clear.hint", "Right-click: select everyone online");
        en.put("bulk.gathered", "%count% players teleported.");
        en.put("bulk.healed", "%count% players healed.");
        en.put("bulk.kicked", "%count% players kicked.");
        en.put("bulk.messaged", "Message sent to %count% players.");
        en.put("bulk.warned", "%count% players warned.");
        en.put("bulk.selected", "%count% players selected.");
        en.put("bulk.added", "%player% added to the selection.");
        en.put("bulk.removed", "%player% removed from the selection.");
        en.put("bulk.cleared", "Selection cleared.");

        en.put("templates.title", "Templates");
        en.put("templates.empty", "No template configured.");
        en.put("templates.next", "Next step:");
        en.put("templates.step", "Step");
        en.put("templates.click", "Click twice to apply");
        en.put("templates.no_escalation", "Escalation disabled: always step 1");
        en.put("templates.applied", "%action% applied to %player%.");
        en.put("templates.failed", "Could not apply the sanction to %player%.");
        en.put("templates.info.title", "How it works");
        en.put("templates.info.line1", "The step comes from what this player already collected.");
        en.put("templates.info.line2", "Edit templates.json to change the ladder.");

        en.put("invedit.title", "Inventory");
        en.put("invedit.save", "Save");
        en.put("invedit.save.hint", "Nothing is written until you click");
        en.put("invedit.discard", "Discard");
        en.put("invedit.discard.hint", "Close without saving");
        en.put("invedit.discarded", "Inventory closed without saving.");
        en.put("invedit.saved", "Inventory of %player% saved.");
        en.put("invedit.failed", "Could not save the inventory of %player%.");
        en.put("invedit.mode.online", "Connected player");
        en.put("invedit.mode.offline", "Stored data");
        en.put("invedit.layout1", "Rows 1-4: inventory and hotbar");
        en.put("invedit.layout2", "Row 5: armour then off-hand");
        en.put("invedit.layout3", "Move and remove here; use Give Item to add");
        en.put("invedit.loading", "Loading...");
        en.put("invedit.no_data", "No stored data for %player%.");
        en.put("invedit.no_data_short", "No stored data");
        en.put("invedit.offline_disabled", "Offline editing is disabled in the config.");
        en.put("invedit.disabled", "The inventory editor is disabled in the config.");

        en.put("deaths.title", "Deaths");
        en.put("deaths.empty", "No death recorded.");
        en.put("deaths.loading", "Loading...");
        en.put("deaths.entry", "Death");
        en.put("deaths.cause", "Cause:");
        en.put("deaths.items", "Stacks:");
        en.put("deaths.xp", "Level:");
        en.put("deaths.count", "deaths");
        en.put("deaths.unknown", "Click to load");
        en.put("deaths.stacks", "stacks");
        en.put("deaths.click_open", "Click to see the items");
        en.put("deaths.layout", "Bag, hotbar, then armour and off-hand");
        en.put("deaths.restore", "Restore");
        en.put("deaths.restore.hint", "Click twice to confirm");
        en.put("deaths.restored", "%count% stacks returned to %player%.");
        en.put("deaths.restore_failed", "Could not restore anything to %player%.");
        en.put("deaths.restore_partial", "%count% stacks did not fit and were skipped.");

        en.put("mail.received", "Message from %from%:");
        en.put("mail.delivered", "Message delivered to %player%.");
        en.put("mail.queued", "Message queued for %player%.");
        en.put("mail.full", "%player% has too many pending messages.");
        en.put("mail.pending", "pending");

        en.put("give.done", "%count%x %item% given to %player%.");
        en.put("give.unknown_item", "Unknown item: %item%");
        en.put("give.empty_hand", "You are not holding anything.");

        en.put("vanish.on", "You are now invisible.");
        en.put("vanish.off", "You are visible again.");
        en.put("vanish.still_on", "You reconnected while vanished.");

        en.put("freeze.title", "FROZEN");
        en.put("freeze.subtitle", "A moderator wants to talk to you");
        en.put("freeze.notice", "You have been frozen. Do not disconnect: answer in chat.");
        en.put("freeze.relog", "You are still frozen. Disconnecting does not lift it: answer in chat.");
        en.put("freeze.actionbar", "Frozen - answer the moderator in chat");
        en.put("freeze.denied", "You cannot do that while frozen.");
        en.put("freeze.released", "You have been released.");
        en.put("freeze.released.title", "Released");
        en.put("freeze.done", "%player% is frozen.");
        en.put("freeze.already", "%player% was already frozen.");
        en.put("freeze.lifted", "%player% has been released.");
        en.put("freeze.not_frozen", "%player% was not frozen.");
        en.put("freeze.flagged", "Frozen");

        en.put("spectate.started", "Spectating %player%.");
        en.put("spectate.stopped", "Back to your position.");
        en.put("spectate.hint", "Use the panel again to stop");
        en.put("spectate.target_left", "%player% disconnected, ending the session.");

        en.put("silent.on", "Silent mode ON: no public announcement.");
        en.put("silent.off", "Silent mode OFF.");
        en.put("spy.cmd.on", "Command spy ON.");
        en.put("spy.cmd.off", "Command spy OFF.");
        en.put("spy.social.on", "Social spy ON.");
        en.put("spy.social.off", "Social spy OFF.");
        en.put("back.none", "No position to return to.");

        en.put("chat.locked", "Chat has been locked by %by%.");
        en.put("chat.unlocked", "Chat has been unlocked by %by%.");
        en.put("chat.locked.blocked", "Chat is locked right now.");
        en.put("chat.cleared", "Chat cleared by %by%.");

        en.put("restart.scheduled", "Restart scheduled in %time%.");
        en.put("restart.cancelled", "The scheduled restart has been cancelled.");
        en.put("restart.warning", "Server restart in %minutes% min (%reason%)");
        en.put("restart.title", "Restart");
        en.put("restart.none", "No restart is scheduled.");
        en.put("broadcast.empty", "No message configured.");
        en.put("broadcast.on", "Auto broadcast ON.");
        en.put("broadcast.off", "Auto broadcast OFF.");

        en.put("prompt.note", "Type the note for %player% (! to pin it):");
        en.put("prompt.mail", "Type the message for %player%:");
        en.put("prompt.ban_reason", "Type the ban reason for %player%:");
        en.put("prompt.freeze_reason", "Type the freeze reason for %player%:");
        en.put("prompt.watch_reason", "Type why %player% is being watched:");
        en.put("prompt.give_item", "Type an item id and an optional count:");
        en.put("prompt.bulk_message", "Type the message for the selection:");
        en.put("prompt.bulk_warn", "Type the warn reason for the selection:");

        en.put("tools.disguise", "Disguise");
        en.put("tools.disguise.hint", "Pick a mob from a grid");
        en.put("disguise.menu.title", "Disguise");
        en.put("disguise.menu.empty", "No living entity found.");
        en.put("disguise.menu.active", "Currently applied");
        en.put("disguise.menu.click", "Click to apply");
        en.put("disguise.menu.clear", "Remove the disguise");
        en.put("disguise.menu.random", "Random mob");
        en.put("disguise.menu.baby", "Baby form");
        en.put("disguise.menu.scale", "Scale:");
        en.put("disguise.menu.scale.hint", "Left: bigger, right: smaller");
        en.put("disguise.menu.name", "Show the mob name");
        en.put("disguise.baby_on", "%player% now appears as a baby.");
        en.put("disguise.baby_off", "%player% is back to the adult form.");
        en.put("disguise.scale_set", "Disguise of %player% scaled to %value%.");
        en.put("disguise.name_on", "The mob name is now shown above %player%.");
        en.put("disguise.name_off", "The mob name above %player% is hidden.");
        en.put("disguise.show", "%player%: %value% (baby: %baby%, scale: %scale%, name: %name%)");
        en.put("disguise.all", "%count% players disguised as %value%.");
        en.put("disguise.random_all", "%count% players given a random disguise.");
        en.put("disguise.clear_all", "%count% disguises removed.");
        en.put("disguise.no_random", "Could not pick a random mob.");
        en.put("disguise.list.empty", "Nobody is disguised.");
        en.put("disguise.list.header", "Disguised players (%count%):");

        translations.put("en", en);

        Map<String, String> fr = new HashMap<>();
        fr.put("menu.title", "Panneau Admin");
        fr.put("menu.filter.all", "Filtre: TOUS");
        fr.put("menu.filter.online", "Filtre: EN LIGNE");
        fr.put("player.online", "En Ligne");
        fr.put("player.offline", "Hors Ligne");
        fr.put("detail.title", "Joueur: %s");
        fr.put("detail.homes", "Homes");
        fr.put("detail.tp_history", "Historique TP");
        fr.put("homes.none", "Aucun Home");
        fr.put("action.tp", "Se TP au Joueur");
        fr.put("action.tp_here", "TP le Joueur Ici");
        fr.put("action.tp_last", "TP Dernière Position");
        fr.put("action.kick", "Expulser Joueur");
        fr.put("action.ban", "Bannir Joueur");
        fr.put("action.unban", "Débannir Joueur");
        fr.put("action.back", "Retour Liste");
        fr.put("action.warn", "Avertir Joueur");
        fr.put("action.warn_list", "Voir Avertissements");
        fr.put("action.search", "Rechercher Joueurs");
        fr.put("action.search.hint", "Cliquez pour chercher par nom");
        fr.put("action.search.prompt", "Tapez un nom de joueur (ou 'cancel') :");
        fr.put("action.search.clear", "Effacer Recherche");
        fr.put("action.search.current", "Filtre actuel :");
        fr.put("action.cancelled", "Action annulée.");
        fr.put("info.full", "Informations Complètes");
        fr.put("info.banned", "Banni");
        fr.put("info.whitelisted", "Whitelisté");
        fr.put("info.last_seen", "Dernière Vue");
        fr.put("misc.yes", "OUI");
        fr.put("misc.no", "NON");
        fr.put("misc.click_tp", "Clic pour TP");
        fr.put("misc.confirm", "Cliquez encore pour confirmer !");
        fr.put("action.invsee", "Voir Inventaire");
        fr.put("action.resetprog", "Reset Progression");
        fr.put("action.clearinv", "Vider Inventaire");
        fr.put("msg.inv_cleared", "Inventaire vidé pour %s");
        fr.put("warn.prompt", "Écrivez la raison dans le chat (ou 'cancel') :");
        fr.put("warn.prompt.cancel", "Tapez 'cancel' pour annuler.");
        fr.put("warn.success", "Joueur averti avec succès.");
        fr.put("warn.list.title", "Avertissements : %s");
        fr.put("warn.list.empty", "Aucun avertissement.");
        fr.put("warn.item.title", "Avertissement #%d");
        fr.put("warn.item.by", "Par : %s");
        fr.put("warn.item.reason", "Raison : %s");
        fr.put("warn.item.date", "Date : %s");
        fr.put("warn.title", "ATTENTION");
        fr.put("warn.subtitle", "Vous avez reçu un avertissement !");
        fr.put("warn.notification", "Vous avez été averti par %s");
        fr.put("warn.deleted", "Avertissement #%d supprimé pour le joueur %s.");
        fr.put("warn.click_delete", "Cliquez pour supprimer");
        fr.put("warn.cleared", "Tous les avertissements supprimés pour %s (%d supprimés).");
        fr.put("error.invalid_index", "Numéro d'avertissement invalide.");
        fr.put("error.no_warns", "Ce joueur n'a aucun avertissement.");
        fr.put("error.invalid_target", "Cible invalide.");
        fr.put("error.player_only", "Cette commande ne peut être utilisée que par un joueur.");
        fr.put("action.mute", "Rendre Muet");
        fr.put("action.unmute", "Retirer le Mute");
        fr.put("mute.hint", "Cliquez pour mute 10 minutes");
        fr.put("mute.remaining", "Temps restant :");
        fr.put("mute.reason", "Raison :");
        fr.put("mute.feedback", "Vous êtes muté. Restant : %time% — Raison : %reason%");
        fr.put("staff.chat.enabled", "Chat staff activé. Tous vos messages vont au canal staff.");
        fr.put("staff.chat.disabled", "Chat staff désactivé. Messages en chat public.");
        fr.put("staff.online", "Staff en ligne (%d) :");
        fr.put("staff.none_online", "Aucun staff en ligne.");
        fr.put("action.jail", "Emprisonner");
        fr.put("action.unjail", "Libérer");
        fr.put("jail.hint", "Cliquez pour emprisonner 30 minutes");
        fr.put("jail.remaining", "Temps restant :");
        fr.put("jail.reason.label", "Raison :");
        fr.put("jail.permanent", "Permanent");
        fr.put("jail.location.set", "Position de la prison définie à votre position !");
        fr.put("jail.no_location", "Aucune prison définie ! Utilisez /arcadia_adminpanel setjail d'abord.");
        fr.put("jail.success", "%player% emprisonné pour %time%.");
        fr.put("jail.unjail.success", "%player% libéré de prison.");
        fr.put("jail.not_jailed", "%player% n'est pas en prison.");
        fr.put("jail.notify", "Vous avez été emprisonné ! Durée : %time% — Raison : %reason%");
        fr.put("jail.notify.permanent", "Vous avez été emprisonné définitivement ! Raison : %reason%");
        fr.put("jail.released", "Vous avez été libéré de prison !");
        fr.put("jail.login.reminder", "Vous êtes toujours en prison. Restant : %time% — Raison : %reason%");
        fr.put("jail.blocked.command", "Vous ne pouvez pas utiliser de commandes en prison.");
        fr.put("jail.list.empty", "Aucun joueur en prison.");
        fr.put("jail.list.header", "Joueurs en prison (%count%) :");
        fr.put("nav.previous", "Précédent");
        fr.put("nav.next", "Suivant");
        fr.put("reload.start", "Rechargement des données admin...");
        fr.put("reload.done", "Rechargement terminé !");
        fr.put("error.open_panel", "Erreur d'ouverture du panneau admin : %s");
        fr.put("warn.reason_prefix", "Raison :");
        fr.put("warn.list_console", "Avertissements pour %s : %d");
        fr.put("misc.admin_action", "Action Admin");
        fr.put("misc.unknown", "Inconnu");
        fr.put("misc.dim", "Dim :");
        fr.put("misc.pos", "Pos :");
        fr.put("misc.server", "Serveur :");
        fr.put("misc.warns_label", "Avertissements :");
        fr.put("misc.warn_count", "%d avertissement(s)");
        fr.put("tp.success", "Téléporté à %.0f, %.0f, %.0f");
        fr.put("search.placeholder", "Rechercher...");
        fr.put("info.last_login", "Dernière connexion :");
        fr.put("info.last_logout", "Dernière déconnexion :");
        fr.put("info.first_seen", "Première fois vu :");
        fr.put("team.browse", "Parcourir les Teams");
        fr.put("team.browse.hint", "Voir toutes les FTB Teams (parties + teams serveur)");
        fr.put("team.list.title", "FTB Teams");
        fr.put("team.list.empty", "Aucune team trouvée.");
        fr.put("team.detail.title", "Détails de la Team");
        fr.put("team.not_found", "Team introuvable (données obsolètes, rechargez).");
        fr.put("team.unavailable", "FTB Teams non détecté");
        fr.put("team.unavailable.hint", "Le dossier ftbteams est introuvable sur ce serveur.");
        fr.put("team.view", "Voir la Team");
        fr.put("team.name", "Nom :");
        fr.put("team.type", "Type :");
        fr.put("team.members", "Membres :");
        fr.put("team.rank", "Rang :");
        fr.put("team.click.view", "Cliquez pour voir les membres");
        fr.put("team.click.tp", "Clic droit : TP à la dernière position");
        fr.put("team.claims", "Claims :");
        fr.put("team.force_loaded", "Force-loaded :");
        fr.put("warn.join.header", "Vous avez %count% avertissement(s) actif(s) :");
        fr.put("warn.join.expires", "expire dans");
        fr.put("warn.join.more", "de plus — tapez /arcadia_adminpanel checkwarn pour tout voir.");
        fr.put("warn.join.cmd_hint", "Pour voir vos avertissements, tapez :");
        fr.put("jail.blocked.teleport", "Vous ne pouvez pas utiliser d'objets ou de blocs de téléportation en prison.");
        fr.put("warn.join.cmd_hover", "Cliquez pour exécuter la commande.");
        fr.put("baton.tooltip.line1", "Clic droit sur un joueur pour l'emprisonner 30 minutes.");
        fr.put("baton.tooltip.line2", "Staff uniquement — nécessite arcadia.adminpanel.jail.");
        fr.put("baton.reason", "Frappé avec la Matraque de Prison");
        fr.put("baton.no_perm", "Vous n'avez pas la permission d'utiliser la Matraque.");
        fr.put("baton.no_self", "Vous ne pouvez pas vous matraquer vous-même.");
        fr.put("baton.no_staff", "Vous ne pouvez pas matraquer un autre membre du staff.");
        fr.put("baton.given", "Matraque de Prison ajoutée à votre inventaire.");
        fr.put("announce.empty", "Le titre de l'annonce ne peut pas être vide.");
        fr.put("announce.success", "Annonce envoyée à %count% joueur(s).");
        // ── 1.2.5 ──────────────────────────────────────────────────────────
        fr.put("action.nextspawn", "Spawn Prochaine Connexion");
        fr.put("nextspawn.hint", "Clic gauche : ce joueur apparaîtra à votre position à sa prochaine connexion.");
        fr.put("nextspawn.set_to", "Défini à :");
        fr.put("nextspawn.left_update", "Clic gauche : mettre à jour à votre position");
        fr.put("nextspawn.right_clear", "Clic droit : annuler");
        fr.put("nextspawn.set", "Spawn de prochaine connexion défini pour %player%.");
        fr.put("nextspawn.cleared", "Spawn de prochaine connexion annulé pour %player%.");
        fr.put("nextspawn.none", "Aucun spawn de prochaine connexion défini pour %player%.");
        fr.put("nextspawn.applied", "Un admin a déplacé votre point de spawn de prochaine connexion.");
        fr.put("nextspawn.list.empty", "Aucun spawn de prochaine connexion en attente.");
        fr.put("nextspawn.list.header", "Spawns de prochaine connexion en attente (%count%) :");
        fr.put("action.gamemode", "Mode de Jeu");
        fr.put("gamemode.current", "Actuel :");
        fr.put("gamemode.cycle", "Cliquez pour changer de mode");
        fr.put("action.heal", "Soigner / Nourrir");
        fr.put("heal.hint", "Clic gauche : soigner · Clic droit : nourrir");
        fr.put("heal.done", "%player% soigné.");
        fr.put("feed.done", "%player% nourri.");
        fr.put("team.filter.show_players", "Afficher les teams joueur");
        fr.put("team.filter.hide_players", "Masquer les teams joueur");
        fr.put("team.filter.players_hint", "Afficher/masquer les teams personnelles dans la liste");
        fr.put("team.member.actions", "Clic gauche : gérer / modérer · Clic droit : TP dernière position");
        fr.put("team.gather", "Rassembler les membres en ligne");
        fr.put("team.gather.hint", "Téléporte tous les membres en ligne de cette team vers toi.");
        fr.put("team.gather.notify", "Tu as été convoqué par %admin%.");
        fr.put("team.gather.done", "%count% membre(s) en ligne de %team% rassemblé(s).");
        fr.put("team.message", "Message à la team");
        fr.put("team.message.hint", "Écris une ligne envoyée à tous les membres en ligne.");
        fr.put("team.message.prompt", "Écris le message à envoyer à %team% (ou « cancel ») :");
        fr.put("team.message.prefix", "Staff :");
        fr.put("team.message.sent", "Message délivré à %count% membre(s) en ligne de %team%.");
        fr.put("jail.radius.current", "Rayon de la zone de prison : %radius% blocs (anti-évasion : %state%)");
        fr.put("jail.radius.set", "Rayon de la zone de prison réglé à %radius% blocs (anti-évasion activé).");
        fr.put("loginqueue.state", "La file d'attente de connexion est actuellement %state%.");
        fr.put("loginqueue.set", "File d'attente de connexion : %state%.");
        fr.put("loginqueue.invalid", "État invalide — utilisez 'on' ou 'off'.");
        // ── Pseudos (name tags) ─────────────────────────────────────────────
        fr.put("nametag.set.color", "Couleur du pseudo de %player% définie sur %value%.");
        fr.put("nametag.set.rgb", "Pseudo de %player% défini en RGB %value%.");
        fr.put("nametag.set.gradient", "Pseudo de %player% défini en dégradé à %value% couleurs.");
        fr.put("nametag.set.effect", "Effet du pseudo de %player% défini sur %value%.");
        fr.put("nametag.set.style_on", "%value% activé sur le pseudo de %player%.");
        fr.put("nametag.set.style_off", "%value% désactivé sur le pseudo de %player%.");
        fr.put("nametag.set.speed", "Vitesse d'animation du pseudo de %player% réglée sur %value%.");
        fr.put("nametag.name.set", "Pseudo affiché de %player% défini sur « %value% ».");
        fr.put("nametag.name.cleared", "Pseudo personnalisé de %player% effacé (retour à son vrai pseudo).");
        fr.put("nametag.name.too_long", "Ce pseudo est trop long (32 caractères maximum).");
        fr.put("nametag.grade.on", "Le grade de %player% est désormais affiché à côté de son pseudo.");
        fr.put("nametag.grade.off", "Le grade de %player% est désormais masqué à côté de son pseudo.");
        fr.put("nametag.reset", "Style du pseudo de %player% réinitialisé.");
        fr.put("nametag.reset_none", "%player% n'avait aucun style de pseudo.");
        fr.put("nametag.show", "%player% : pseudo=%name% grade=%grade% effet=%effect% couleurs=[%colors%] vitesse=%speed% styles=%flags%");
        fr.put("nametag.show_none", "%player% utilise le pseudo par défaut (aucun style).");
        fr.put("nametag.exempt_on", "%player% est désormais exempté — son pseudo est toujours visible.");
        fr.put("nametag.exempt_off", "%player% n'est plus exempté du masquage des pseudos.");
        fr.put("nametag.hide.state", "Le masquage des pseudos derrière les murs est actuellement %state%.");
        fr.put("nametag.hide.set", "Masquage des pseudos derrière les murs : %state%.");
        fr.put("nametag.hideall.state", "Le masquage total des pseudos (mode event) est actuellement %state%.");
        fr.put("nametag.hideall.set", "Masquage total des pseudos (mode event) : %state% — tous les pseudos des joueurs sont concernés.");
        fr.put("nametag.forcehide_on", "Le pseudo de %player% est désormais masqué en permanence pour tout le monde.");
        fr.put("nametag.forcehide_off", "Le pseudo de %player% n'est plus masqué en permanence.");
        fr.put("nametag.invalid_color", "Nom de couleur invalide. Utilisez une couleur vanilla : red, gold, aqua…");
        fr.put("nametag.invalid_hex", "Couleur hex invalide. Utilisez #RRGGBB (ex. #FF8800).");
        fr.put("nametag.invalid_effect", "Effet inconnu. Essayez : solid, gradient, rainbow, breathing, chase, wave, blink, fade, typewriter, random.");
        fr.put("nametag.invalid_flag", "Style inconnu. Utilisez : bold, italic, underline, strikethrough, obfuscated.");
        fr.put("disguise.set", "%player% est déguisé en %value%.");
        fr.put("disguise.cleared", "Déguisement de %player% retiré.");
        fr.put("disguise.none", "%player% n'était pas déguisé.");
        fr.put("disguise.invalid_entity", "Type d'entité inconnu « %value% ». Utilisez un id comme minecraft:pig.");
        fr.put("disguise.not_living", "« %value% » n'est pas un mob vivant et ne peut pas servir de déguisement.");
        // ── 1.3.0 ───────────────────────────────────────────────────────────
        fr.put("action.close", "Fermer");
        fr.put("list.empty", "Rien à afficher");
        fr.put("misc.on", "ACTIVÉ");
        fr.put("misc.off", "DÉSACTIVÉ");
        fr.put("error.player_offline", "Ce joueur n'est pas connecté.");

        fr.put("tools.title", "Outils Staff");
        fr.put("tools.hint", "Outils serveur et vos propres bascules");
        fr.put("tools.status", "État du serveur");
        fr.put("tools.status.tps", "TPS");
        fr.put("tools.status.mspt", "MSPT");
        fr.put("tools.status.players", "Joueurs");
        fr.put("tools.status.memory", "Mémoire");
        fr.put("tools.status.entities", "Entités");
        fr.put("tools.players", "Liste des joueurs");
        fr.put("tools.players.hint", "Retour à la grille des joueurs");
        fr.put("tools.audit", "Journal d'audit");
        fr.put("tools.audit.entries", "entrées");
        fr.put("tools.bans", "Liste des bans");
        fr.put("tools.bans.count", "bans");
        fr.put("tools.watchlist", "Liste de surveillance");
        fr.put("tools.watchlist.count", "surveillés");
        fr.put("tools.sessions", "Temps de jeu");
        fr.put("tools.sessions.hint", "Sessions et classement du temps de jeu");
        fr.put("tools.afk", "Joueurs AFK");
        fr.put("tools.afk.count", "inactifs");
        fr.put("tools.alts", "Connexions partagées");
        fr.put("tools.alts.count", "groupes");
        fr.put("tools.alts.shared", "comptes correspondants");
        fr.put("tools.alts.privacy", "Aucune adresse n'est stockée ni affichée");
        fr.put("tools.clientmods", "Mods client");
        fr.put("tools.clientmods.count", "rapports");
        fr.put("tools.performance", "Performances");
        fr.put("tools.performance.hint", "TPS, chunks chargés, joueurs lourds");
        fr.put("tools.chunks", "Navigateur de chunks");
        fr.put("tools.chunks.hint", "Claims et chunks force-loaded");
        fr.put("tools.world", "Contrôle du monde");
        fr.put("tools.world.hint", "Heure, météo, difficulté, gamerules");
        fr.put("tools.chat.lock", "Verrouiller le chat");
        fr.put("tools.chat.unlock", "Déverrouiller le chat");
        fr.put("tools.chat.lock.hint", "Geler le chat public");
        fr.put("tools.chat.locked_by", "Verrouillé par");
        fr.put("tools.chat.clear", "Vider le chat");
        fr.put("tools.chat.clear.hint", "Fait défiler le chat de tout le monde");
        fr.put("tools.restart", "Redémarrage programmé");
        fr.put("tools.restart.hint", "Gauche : dans 15 min, droit : dans 5 min");
        fr.put("tools.restart.pending", "Redémarrage dans");
        fr.put("tools.restart.click", "Cliquez à nouveau pour annuler");
        fr.put("tools.broadcast", "Annonces automatiques");
        fr.put("tools.broadcast.count", "messages");
        fr.put("tools.vanish", "Invisibilité");
        fr.put("tools.silent", "Mode silencieux");
        fr.put("tools.silent.hint", "Aucune annonce publique, toujours tracé");
        fr.put("tools.cmdspy", "Espion de commandes");
        fr.put("tools.socialspy", "Espion de messages privés");
        fr.put("tools.loginqueue", "File d'attente");
        fr.put("tools.loginqueue.hint", "Throttle de connexion post-reboot");
        fr.put("tools.loginqueue.auto", "Fenêtre automatique :");
        fr.put("tools.selection", "Sélection");
        fr.put("tools.selection.count", "sélectionnés");
        fr.put("tools.selection.hint", "Shift-clic sur les têtes pour sélectionner");
        fr.put("tools.back", "Retour");
        fr.put("tools.back.count", "positions enregistrées");
        fr.put("tools.radar", "Radar de proximité");
        fr.put("tools.radar.hint", "Qui est à proximité");

        fr.put("tools.player", "Outils joueur");
        fr.put("tools.player.hint", "Historique, notes, gel, inventaire et plus");
        fr.put("tools.player.open", "Cliquez pour ouvrir");
        fr.put("tools.player.rows", "Enquêter / Intervenir / Assister, une ligne chacun");
        fr.put("tools.group.investigate", "Enquêter");
        fr.put("tools.group.investigate.hint", "Comprendre ce qui s'est passé");
        fr.put("tools.group.intervene", "Intervenir");
        fr.put("tools.group.intervene.hint", "Agir sur ce joueur maintenant");
        fr.put("tools.group.assist", "Assister");
        fr.put("tools.group.assist.hint", "Lui rendre quelque chose ou le joindre");
        fr.put("tools.group.server", "Serveur");
        fr.put("tools.group.server.hint", "Performances, monde, chat et planification");
        fr.put("tools.group.self", "Vos bascules");
        fr.put("tools.group.self.hint", "Réglages qui ne concernent que vous");
        fr.put("tools.requires_online", "Nécessite que le joueur soit connecté");
        fr.put("tools.offline_release", "Hors ligne : libérer lève le gel pour sa prochaine connexion");
        fr.put("tools.deaths.hint", "Ses dernières morts et ce qu'il portait");
        fr.put("tools.back.sheet", "Retour à la fiche du joueur");
        fr.put("tools.history", "Historique des sanctions");
        fr.put("tools.history.count", "sanctions");
        fr.put("tools.notes", "Notes staff");
        fr.put("tools.watch.add", "Ajouter à la surveillance");
        fr.put("tools.watch.remove", "Retirer de la surveillance");
        fr.put("tools.freeze", "Geler");
        fr.put("tools.freeze.hint", "Immobiliser le joueur pour un screenshare");
        fr.put("tools.unfreeze", "Libérer");
        fr.put("tools.unfreeze.hint", "Terminer le screenshare");
        fr.put("tools.spectate", "Observer");
        fr.put("tools.spectate.stop", "Arrêter d'observer");
        fr.put("tools.spectate.hint", "Vous ramène à votre position");
        fr.put("tools.tempban", "Ban temporaire");
        fr.put("tools.tempban.hint", "Clic droit pour un ban définitif");
        fr.put("tools.templates", "Modèles de sanction");
        fr.put("tools.templates.hint", "Raisons prédéfinies avec escalade");
        fr.put("tools.select.add", "Ajouter à la sélection");
        fr.put("tools.select.remove", "Retirer de la sélection");
        fr.put("tools.invedit", "Éditeur d'inventaire");
        fr.put("tools.invedit.hint", "Consulter et modifier, puis sauvegarder");
        fr.put("tools.deaths", "Instantanés de mort");
        fr.put("tools.give", "Donner un objet");
        fr.put("tools.give.hint", "Gauche : objet en main, droit : par id");
        fr.put("tools.mail", "Courrier hors ligne");

        fr.put("menu.filter", "Filtre :");
        fr.put("menu.legend", "Comment fonctionne cet écran");
        fr.put("menu.legend.open", "Clic gauche sur une tête : ouvrir sa fiche");
        fr.put("menu.legend.select", "Clic droit ou shift-clic : ajouter à la sélection");
        fr.put("menu.legend.cycle", "Filtre et tri : clic gauche avance, clic droit recule");
        fr.put("menu.legend.colours", "Couleur du nom :");
        fr.put("menu.legend.online", "en ligne");
        fr.put("menu.legend.afk", "AFK");
        fr.put("menu.legend.offline", "hors ligne");
        fr.put("menu.legend.selected", "sélectionné");
        fr.put("menu.filter.results", "résultats");
        fr.put("menu.filter.cycle", "Clic droit pour revenir en arrière");
        fr.put("menu.filter.all", "Tous");
        fr.put("menu.filter.online", "En ligne");
        fr.put("menu.filter.offline", "Hors ligne");
        fr.put("menu.filter.jailed", "En prison");
        fr.put("menu.filter.muted", "Mute");
        fr.put("menu.filter.banned", "Bannis");
        fr.put("menu.filter.warned", "Avertis");
        fr.put("menu.filter.watched", "Surveillés");
        fr.put("menu.filter.frozen", "Gelés");
        fr.put("menu.filter.vanished", "Invisibles");
        fr.put("menu.filter.afk", "AFK");
        fr.put("menu.filter.selected", "Sélectionnés");
        fr.put("menu.sort", "Tri :");
        fr.put("menu.sort.cycle", "Clic droit pour revenir en arrière");
        fr.put("menu.sort.name", "Nom");
        fr.put("menu.sort.last_seen", "Dernière connexion");
        fr.put("menu.sort.playtime", "Temps de jeu");
        fr.put("menu.sort.warns", "Avertissements");
        fr.put("menu.select.hint", "Shift-clic ou clic droit pour sélectionner");
        fr.put("menu.mark.jailed", "En prison");
        fr.put("menu.mark.muted", "Mute");
        fr.put("menu.mark.frozen", "Gelé");
        fr.put("menu.mark.vanished", "Invisible");
        fr.put("menu.mark.watched", "Surveillé");
        fr.put("menu.mark.warns", "avertissements");

        fr.put("audit.title", "Journal d'audit");
        fr.put("audit.empty", "Aucune action enregistrée pour le moment.");
        fr.put("audit.by", "Par");
        fr.put("audit.duration", "Durée :");
        fr.put("audit.detail", "Détail :");
        fr.put("audit.silent", "silencieux");
        fr.put("audit.click_actor", "Clic droit : les actions de ce staff");
        fr.put("audit.filter", "Filtre");
        fr.put("audit.filter.clear", "Cliquez pour tout voir");
        fr.put("audit.scope.all", "Toutes les actions");
        fr.put("audit.scope.target", "Un joueur");
        fr.put("audit.scope.actor", "Un membre du staff");
        fr.put("audit.action.warn", "a averti");
        fr.put("audit.action.warn_delete", "a supprimé un avertissement de");
        fr.put("audit.action.warn_clear", "a vidé les avertissements de");
        fr.put("audit.action.mute", "a mute");
        fr.put("audit.action.unmute", "a unmute");
        fr.put("audit.action.kick", "a expulsé");
        fr.put("audit.action.ban", "a banni");
        fr.put("audit.action.tempban", "a banni temporairement");
        fr.put("audit.action.unban", "a débanni");
        fr.put("audit.action.jail", "a emprisonné");
        fr.put("audit.action.unjail", "a libéré");
        fr.put("audit.action.freeze", "a gelé");
        fr.put("audit.action.unfreeze", "a dégelé");
        fr.put("audit.action.vanish", "a basculé l'invisibilité sur");
        fr.put("audit.action.spectate", "a observé");
        fr.put("audit.action.spy", "a utilisé un espion sur");
        fr.put("audit.action.invsee", "a consulté l'inventaire de");
        fr.put("audit.action.clear_inv", "a vidé l'inventaire de");
        fr.put("audit.action.inv_edit", "a modifié l'inventaire de");
        fr.put("audit.action.restore_death", "a restauré une mort de");
        fr.put("audit.action.give_item", "a donné un objet à");
        fr.put("audit.action.reset_progress", "a réinitialisé la progression de");
        fr.put("audit.action.gamemode", "a changé le mode de jeu de");
        fr.put("audit.action.heal", "a soigné");
        fr.put("audit.action.teleport", "a téléporté");
        fr.put("audit.action.next_spawn", "a défini un spawn de connexion pour");
        fr.put("audit.action.note_add", "a ajouté une note sur");
        fr.put("audit.action.note_delete", "a supprimé une note sur");
        fr.put("audit.action.watch_add", "a mis sous surveillance");
        fr.put("audit.action.watch_remove", "a retiré de la surveillance");
        fr.put("audit.action.mail_send", "a envoyé un courrier à");
        fr.put("audit.action.announce", "a annoncé");
        fr.put("audit.action.chat_lock", "a changé le verrou du chat");
        fr.put("audit.action.chat_clear", "a vidé le chat");
        fr.put("audit.action.world_edit", "a changé un réglage du monde");
        fr.put("audit.action.restart", "a changé le redémarrage programmé");
        fr.put("audit.action.bulk", "a lancé une action groupée");
        fr.put("audit.action.nametag", "a changé le pseudo de");
        fr.put("audit.action.disguise", "a déguisé");
        fr.put("audit.action.login_queue", "a changé la file d'attente");
        fr.put("audit.action.setjail", "a déplacé la prison");
        fr.put("audit.action.reload", "a rechargé le panel");

        fr.put("history.title", "Historique");
        fr.put("history.empty", "Aucune sanction enregistrée.");
        fr.put("history.active", "Actuellement active");
        fr.put("history.warns", "Avertissements :");
        fr.put("history.sanctions", "Autres sanctions :");
        fr.put("history.total", "Total :");
        fr.put("history.audit", "Journal complet");
        fr.put("history.audit.hint", "Toutes les actions, pas seulement les sanctions");

        fr.put("notes.title", "Notes");
        fr.put("notes.empty", "Aucune note pour le moment.");
        fr.put("notes.count", "notes");
        fr.put("notes.add", "Ajouter une note");
        fr.put("notes.add.hint", "Écrivez-la dans le chat");
        fr.put("notes.pin.hint", "Commencez par ! pour l'épingler");
        fr.put("notes.pinned", "Épinglée");
        fr.put("notes.click_delete", "Clic droit pour supprimer");
        fr.put("note.added", "Note ajoutée sur %player%.");

        fr.put("watchlist.title", "Surveillance");
        fr.put("watchlist.empty", "Personne n'est surveillé.");
        fr.put("watchlist.click", "Gauche : fiche, droit : retirer");
        fr.put("watchlist.added", "%player% est désormais sous surveillance.");
        fr.put("watchlist.removed", "%player% n'est plus surveillé.");
        fr.put("watchlist.not_watched", "%player% n'était pas surveillé.");
        fr.put("watchlist.join", "Le joueur surveillé %player% vient de se connecter (signalé par %by%)");
        fr.put("watchlist.flagged", "Sous surveillance");

        fr.put("banlist.title", "Bans");
        fr.put("banlist.empty", "Personne n'est banni.");
        fr.put("banlist.permanent", "Définitif");
        fr.put("banlist.expires", "Expire dans");
        fr.put("banlist.click_unban", "Cliquez pour débannir");
        fr.put("banlist.unbanned", "%player% a été débanni.");
        fr.put("ban.applied", "%player% a été banni.");

        fr.put("sessions.title", "Temps de jeu");
        fr.put("sessions.empty", "Aucune session enregistrée.");
        fr.put("sessions.playtime", "Temps de jeu :");
        fr.put("sessions.count", "sessions");
        fr.put("sessions.average", "Moyenne :");
        fr.put("sessions.last", "Dernière connexion :");
        fr.put("sessions.sort", "Tri");
        fr.put("sessions.sort.playtime", "Par temps de jeu");
        fr.put("sessions.sort.recent", "Par dernière connexion");

        fr.put("afk.title", "Joueurs AFK");
        fr.put("afk.empty", "Personne n'est inactif.");
        fr.put("afk.duration", "Inactif depuis");
        fr.put("afk.click", "Gauche : fiche, droit : téléportation");
        fr.put("afk.threshold", "Seuil");

        fr.put("alts.title", "Connexions partagées");
        fr.put("alts.empty", "Aucune connexion partagée trouvée.");
        fr.put("alts.group", "Groupe");
        fr.put("alts.accounts", "comptes");
        fr.put("alts.has_banned", "Contient un compte banni");
        fr.put("alts.click", "Cliquez pour voir les comptes");
        fr.put("alts.privacy.title", "À propos de ces données");
        fr.put("alts.privacy.line1", "Les comptes sont groupés par une empreinte hachée.");
        fr.put("alts.privacy.line2", "Aucune adresse n'est stockée ni affichée.");
        fr.put("alt.ban_evasion", "%player% partage une connexion avec le(s) compte(s) banni(s) : %accounts%");

        fr.put("clientmods.title", "Mods client");
        fr.put("clientmods.empty", "Aucun client n'a fait de rapport.");
        fr.put("clientmods.none", "Ce client n'a rien déclaré.");
        fr.put("clientmods.no_report", "Aucun rapport (mod non installé)");
        fr.put("clientmods.mods", "mods");
        fr.put("clientmods.click", "Cliquez pour voir la liste");
        fr.put("clientmods.declared", "Déclaré par le client");
        fr.put("clientmods.blacklisted", "Sur la liste noire");
        fr.put("clientmods.flagged_short", "Mod de la liste noire détecté");
        fr.put("clientmods.flagged", "%player% utilise un mod de la liste noire : %mods%");
        fr.put("clientmods.disclaimer.title", "À propos de ces données");
        fr.put("clientmods.disclaimer.line1", "Auto-déclaré par le client.");
        fr.put("clientmods.disclaimer.line2", "Un client modifié peut mentir.");

        fr.put("perf.title", "Performances");
        fr.put("perf.summary", "Résumé");
        fr.put("perf.mspt_mean", "MSPT moyen :");
        fr.put("perf.mspt_peak", "MSPT max :");
        fr.put("perf.entities_total", "Entités totales :");
        fr.put("perf.chunks_total", "Chunks chargés :");
        fr.put("perf.sampled", "Mesuré il y a");
        fr.put("perf.entities", "entités");
        fr.put("perf.chunks", "chunks");
        fr.put("perf.forced", "force-loaded");
        fr.put("perf.hot_chunks", "Chunks les plus chargés");
        fr.put("perf.hot_chunks.hint", "Plus forte concentration d'entités");
        fr.put("perf.chunk", "Chunk");
        fr.put("perf.nearest", "Le plus proche :");
        fr.put("perf.nearby", "Entités à proximité :");
        fr.put("perf.afk", "AFK");
        fr.put("perf.refresh", "Recalculer");

        fr.put("chunks.title", "Chunks");
        fr.put("chunks.no_teams", "Aucune donnée FTB Chunks.");
        fr.put("chunks.no_forced", "Aucun chunk force-loaded.");
        fr.put("chunks.claims", "Claims :");
        fr.put("chunks.forced", "Force-loaded :");
        fr.put("chunks.members", "Membres :");
        fr.put("chunks.block_pos", "Bloc");
        fr.put("chunks.view", "Vue");
        fr.put("chunks.view.teams", "Par team");
        fr.put("chunks.view.forced", "Chunks forcés vanilla");
        fr.put("chunks.summary", "Totaux");
        fr.put("chunks.vanilla_forced", "Forcés vanilla :");

        fr.put("world.title", "Contrôle du monde");
        fr.put("world.current_time", "Heure :");
        fr.put("world.current_weather", "Météo :");
        fr.put("world.scope_dimension", "S'applique à cette dimension");
        fr.put("world.scope_server", "S'applique à tout le serveur");
        fr.put("world.time.dawn", "Aube");
        fr.put("world.time.day", "Jour");
        fr.put("world.time.noon", "Midi");
        fr.put("world.time.dusk", "Crépuscule");
        fr.put("world.time.night", "Nuit");
        fr.put("world.time.midnight", "Minuit");
        fr.put("world.weather.clear", "Dégagé");
        fr.put("world.weather.rain", "Pluie");
        fr.put("world.weather.thunder", "Orage");
        fr.put("world.difficulty", "Difficulté :");
        fr.put("world.difficulty.hint", "Cliquez pour changer");
        fr.put("world.difficulty.peaceful", "Paisible");
        fr.put("world.difficulty.easy", "Facile");
        fr.put("world.difficulty.normal", "Normal");
        fr.put("world.difficulty.hard", "Difficile");

        fr.put("radar.title", "Radar");
        fr.put("radar.empty", "Personne à portée.");
        fr.put("radar.blocks", "blocs");
        fr.put("radar.range", "Portée");
        fr.put("radar.vanished", "Invisible");
        fr.put("radar.click_detail", "Clic droit : fiche du joueur");

        fr.put("bulk.title", "Actions groupées");
        fr.put("bulk.empty", "Aucune sélection. Shift-clic sur les têtes dans la grille.");
        fr.put("bulk.targets", "cibles");
        fr.put("bulk.click_remove", "Cliquez pour retirer");
        fr.put("bulk.message", "Message à tous");
        fr.put("bulk.gather", "Rassembler ici");
        fr.put("bulk.heal", "Soigner tout le monde");
        fr.put("bulk.warn", "Avertir tout le monde");
        fr.put("bulk.kick", "Expulser tout le monde");
        fr.put("bulk.kick.hint", "Cliquez deux fois pour confirmer");
        fr.put("bulk.clear", "Vider la sélection");
        fr.put("bulk.clear.hint", "Clic droit : sélectionner tous les connectés");
        fr.put("bulk.gathered", "%count% joueurs téléportés.");
        fr.put("bulk.healed", "%count% joueurs soignés.");
        fr.put("bulk.kicked", "%count% joueurs expulsés.");
        fr.put("bulk.messaged", "Message envoyé à %count% joueurs.");
        fr.put("bulk.warned", "%count% joueurs avertis.");
        fr.put("bulk.selected", "%count% joueurs sélectionnés.");
        fr.put("bulk.added", "%player% ajouté à la sélection.");
        fr.put("bulk.removed", "%player% retiré de la sélection.");
        fr.put("bulk.cleared", "Sélection vidée.");

        fr.put("templates.title", "Modèles");
        fr.put("templates.empty", "Aucun modèle configuré.");
        fr.put("templates.next", "Prochain palier :");
        fr.put("templates.step", "Palier");
        fr.put("templates.click", "Cliquez deux fois pour appliquer");
        fr.put("templates.no_escalation", "Escalade désactivée : toujours le palier 1");
        fr.put("templates.applied", "%action% appliqué à %player%.");
        fr.put("templates.failed", "Impossible d'appliquer la sanction à %player%.");
        fr.put("templates.info.title", "Fonctionnement");
        fr.put("templates.info.line1", "Le palier dépend de ce que ce joueur a déjà accumulé.");
        fr.put("templates.info.line2", "Modifiez templates.json pour changer l'échelle.");

        fr.put("invedit.title", "Inventaire");
        fr.put("invedit.save", "Sauvegarder");
        fr.put("invedit.save.hint", "Rien n'est écrit avant ce clic");
        fr.put("invedit.discard", "Abandonner");
        fr.put("invedit.discard.hint", "Fermer sans sauvegarder");
        fr.put("invedit.discarded", "Inventaire fermé sans sauvegarde.");
        fr.put("invedit.saved", "Inventaire de %player% sauvegardé.");
        fr.put("invedit.failed", "Impossible de sauvegarder l'inventaire de %player%.");
        fr.put("invedit.mode.online", "Joueur connecté");
        fr.put("invedit.mode.offline", "Données stockées");
        fr.put("invedit.layout1", "Lignes 1-4 : inventaire et barre d'action");
        fr.put("invedit.layout2", "Ligne 5 : armure puis seconde main");
        fr.put("invedit.layout3", "Déplacer et retirer ici ; Donner un objet pour ajouter");
        fr.put("invedit.loading", "Chargement...");
        fr.put("invedit.no_data", "Aucune donnée stockée pour %player%.");
        fr.put("invedit.no_data_short", "Aucune donnée stockée");
        fr.put("invedit.offline_disabled", "L'édition hors ligne est désactivée dans la config.");
        fr.put("invedit.disabled", "L'éditeur d'inventaire est désactivé dans la config.");

        fr.put("deaths.title", "Morts");
        fr.put("deaths.empty", "Aucune mort enregistrée.");
        fr.put("deaths.loading", "Chargement...");
        fr.put("deaths.entry", "Mort");
        fr.put("deaths.cause", "Cause :");
        fr.put("deaths.items", "Piles :");
        fr.put("deaths.xp", "Niveau :");
        fr.put("deaths.count", "morts");
        fr.put("deaths.unknown", "Cliquez pour charger");
        fr.put("deaths.stacks", "piles");
        fr.put("deaths.click_open", "Cliquez pour voir les objets");
        fr.put("deaths.layout", "Sac, barre d'action, puis armure et main gauche");
        fr.put("deaths.restore", "Restaurer");
        fr.put("deaths.restore.hint", "Cliquez deux fois pour confirmer");
        fr.put("deaths.restored", "%count% piles rendues à %player%.");
        fr.put("deaths.restore_failed", "Impossible de restaurer quoi que ce soit à %player%.");
        fr.put("deaths.restore_partial", "%count% piles ne rentraient pas et ont été ignorées.");

        fr.put("mail.received", "Message de %from% :");
        fr.put("mail.delivered", "Message remis à %player%.");
        fr.put("mail.queued", "Message en attente pour %player%.");
        fr.put("mail.full", "%player% a trop de messages en attente.");
        fr.put("mail.pending", "en attente");

        fr.put("give.done", "%count%x %item% donné à %player%.");
        fr.put("give.unknown_item", "Objet inconnu : %item%");
        fr.put("give.empty_hand", "Vous n'avez rien en main.");

        fr.put("vanish.on", "Vous êtes désormais invisible.");
        fr.put("vanish.off", "Vous êtes de nouveau visible.");
        fr.put("vanish.still_on", "Vous vous êtes reconnecté en étant invisible.");

        fr.put("freeze.title", "GELÉ");
        fr.put("freeze.subtitle", "Un modérateur veut vous parler");
        fr.put("freeze.notice", "Vous avez été gelé. Ne vous déconnectez pas : répondez dans le chat.");
        fr.put("freeze.relog", "Vous êtes toujours gelé. Se déconnecter ne lève pas le gel : répondez dans le chat.");
        fr.put("freeze.actionbar", "Gelé - répondez au modérateur dans le chat");
        fr.put("freeze.denied", "Vous ne pouvez pas faire ça pendant que vous êtes gelé.");
        fr.put("freeze.released", "Vous avez été libéré.");
        fr.put("freeze.released.title", "Libéré");
        fr.put("freeze.done", "%player% est gelé.");
        fr.put("freeze.already", "%player% était déjà gelé.");
        fr.put("freeze.lifted", "%player% a été libéré.");
        fr.put("freeze.not_frozen", "%player% n'était pas gelé.");
        fr.put("freeze.flagged", "Gelé");

        fr.put("spectate.started", "Vous observez %player%.");
        fr.put("spectate.stopped", "Retour à votre position.");
        fr.put("spectate.hint", "Repassez par le panel pour arrêter");
        fr.put("spectate.target_left", "%player% s'est déconnecté, fin de la session.");

        fr.put("silent.on", "Mode silencieux ACTIVÉ : aucune annonce publique.");
        fr.put("silent.off", "Mode silencieux DÉSACTIVÉ.");
        fr.put("spy.cmd.on", "Espion de commandes ACTIVÉ.");
        fr.put("spy.cmd.off", "Espion de commandes DÉSACTIVÉ.");
        fr.put("spy.social.on", "Espion de messages privés ACTIVÉ.");
        fr.put("spy.social.off", "Espion de messages privés DÉSACTIVÉ.");
        fr.put("back.none", "Aucune position où revenir.");

        fr.put("chat.locked", "Le chat a été verrouillé par %by%.");
        fr.put("chat.unlocked", "Le chat a été déverrouillé par %by%.");
        fr.put("chat.locked.blocked", "Le chat est verrouillé pour le moment.");
        fr.put("chat.cleared", "Chat vidé par %by%.");

        fr.put("restart.scheduled", "Redémarrage programmé dans %time%.");
        fr.put("restart.cancelled", "Le redémarrage programmé a été annulé.");
        fr.put("restart.warning", "Redémarrage du serveur dans %minutes% min (%reason%)");
        fr.put("restart.title", "Redémarrage");
        fr.put("restart.none", "Aucun redémarrage n'est programmé.");
        fr.put("broadcast.empty", "Aucun message configuré.");
        fr.put("broadcast.on", "Annonces automatiques ACTIVÉES.");
        fr.put("broadcast.off", "Annonces automatiques DÉSACTIVÉES.");

        fr.put("prompt.note", "Écrivez la note sur %player% (! pour l'épingler) :");
        fr.put("prompt.mail", "Écrivez le message pour %player% :");
        fr.put("prompt.ban_reason", "Écrivez la raison du ban de %player% :");
        fr.put("prompt.freeze_reason", "Écrivez la raison du gel de %player% :");
        fr.put("prompt.watch_reason", "Écrivez pourquoi %player% est surveillé :");
        fr.put("prompt.give_item", "Écrivez un id d'objet et éventuellement une quantité :");
        fr.put("prompt.bulk_message", "Écrivez le message pour la sélection :");
        fr.put("prompt.bulk_warn", "Écrivez la raison de l'avertissement pour la sélection :");

        fr.put("tools.disguise", "Déguisement");
        fr.put("tools.disguise.hint", "Choisir un mob dans une grille");
        fr.put("disguise.menu.title", "Déguisement");
        fr.put("disguise.menu.empty", "Aucune entité vivante trouvée.");
        fr.put("disguise.menu.active", "Actuellement appliqué");
        fr.put("disguise.menu.click", "Cliquez pour appliquer");
        fr.put("disguise.menu.clear", "Retirer le déguisement");
        fr.put("disguise.menu.random", "Mob aléatoire");
        fr.put("disguise.menu.baby", "Forme bébé");
        fr.put("disguise.menu.scale", "Échelle :");
        fr.put("disguise.menu.scale.hint", "Gauche : plus grand, droit : plus petit");
        fr.put("disguise.menu.name", "Afficher le nom du mob");
        fr.put("disguise.baby_on", "%player% apparaît désormais en bébé.");
        fr.put("disguise.baby_off", "%player% est revenu à la forme adulte.");
        fr.put("disguise.scale_set", "Déguisement de %player% mis à l'échelle %value%.");
        fr.put("disguise.name_on", "Le nom du mob est désormais affiché au-dessus de %player%.");
        fr.put("disguise.name_off", "Le nom du mob au-dessus de %player% est masqué.");
        fr.put("disguise.show", "%player% : %value% (bébé : %baby%, échelle : %scale%, nom : %name%)");
        fr.put("disguise.all", "%count% joueurs déguisés en %value%.");
        fr.put("disguise.random_all", "%count% joueurs ont reçu un déguisement aléatoire.");
        fr.put("disguise.clear_all", "%count% déguisements retirés.");
        fr.put("disguise.no_random", "Impossible de tirer un mob au hasard.");
        fr.put("disguise.list.empty", "Personne n'est déguisé.");
        fr.put("disguise.list.header", "Joueurs déguisés (%count%) :");

        translations.put("fr", fr);
    }

    public static String getText(String key, ServerPlayer player) {
        String locale = "en";
        try {
            if (player != null && player.clientInformation() != null) {
                String lang = player.clientInformation().language();
                if (lang != null && lang.toLowerCase().startsWith("fr")) {
                    locale = "fr";
                }
            }
        } catch (Exception ignored) {}
        return getText(key, locale);
    }

    public static String getText(String key, String locale) {
        Map<String, String> map = translations.getOrDefault(locale, translations.get("en"));
        return map.getOrDefault(key, key);
    }

    public static Component getComponent(String key, ServerPlayer player) {
        return Component.literal(getText(key, player));
    }

    private LanguageHelper() {}
}
